spring:
  config:
    #import: optional:configserver:http://localhost:8888
    import: optional:configserver:http://config-server:8888
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:docker}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true